Fix build error with gcc 11.3 - arises when updating yocto to mickledore
caddr_t is defined in sys/types.h. For gcc 10, the stdio.h includes
sys/types.h, in contrast, gcc 11 includes sys/_types.h. The
fsl_sbrk.c includes stdio.h, then it can't see caddr_t for gcc 11,
need add explicitly. - This patch includes sys/types.h

Signed-off-by: Jason Yu <zejiang.yu@nxp.com>

backported from nxp-mcuxpresso/mcux-sdk, https://github.com/nxp-mcuxpresso/mcux-sdk/commit/197fbf8122ca960ad7517056ec938ea5871c13e5

Fixes:

| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:22:1: error: unknown type name 'caddr_t'
|    22 | caddr_t _sbrk(int incr);
|       | ^~~~~~~
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:23:1: error: unknown type name 'caddr_t'
|    23 | caddr_t _sbrk(int incr)
|       | ^~~~~~~
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c: In function '_sbrk':
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:29:5: error: unknown type name 'caddr_t'
|    29 |     caddr_t ret;
|       |     ^~~~~~~
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:42:16: error: 'caddr_t' undeclared (first use in this function)
|    42 |         ret = (caddr_t)-1;
|       |                ^~~~~~~
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:42:16: note: each undeclared identifier is reported only once for each function it appears in
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:48:24: error: expected ';' before 'prev_heap_end'
|    48 |         ret = (caddr_t)prev_heap_end;
|       |                        ^~~~~~~~~~~~~
|       |                        ;
| /home/davisroman/src/p2/mickledore/build/tmp/work/armv8a-poky-linux/ccu-m4-firmware/1.0-r0/git/devices/MIMX8DL1/utilities/fsl_sbrk.c:28:11: warning: variable 'prev_heap_end' set but not used [-Wunused-but-set-variable]
|    28 |     char *prev_heap_end;
|       |           ^~~~~~~~~~~~~